In [2]:
from model import Model
from parameters import parameters as par
from modules.interp import interp_3d
import numpy as np
from scipy.interpolate import RegularGridInterpolator
from numba import njit

In [2]:
m = Model()
m.solve(par)

/Users/Jeppe/.local/share/virtualenvs/dypa_termpaper-laBhpRgB/lib/python3.7/site-packages/scipy/optimize/_minimize.py:761: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  "defaulting to absolute tolerance.", RuntimeWarning)


choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)


/Users/Jeppe/.local/share/virtualenvs/dypa_termpaper-laBhpRgB/lib/python3.7/site-packages/scipy/optimize/_minimize.py:761: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  "defaulting to absolute tolerance.", RuntimeWarning)


choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009

choicetuple(c=190983.62365904142, kappa=0.0, i=0.0)
choicetuple(c=190983.62365904142, kappa=0.0, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=0.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.0, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.0, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.0, i=0.0)
choicetuple(c=190983.62365904142, kappa=0.0, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=0.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=1.0)


({90: array([15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
         15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
         15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
         15.04169525, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
         20.22339078, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
         20.22339078, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
         20.22339078, 20.22339078, 22.01701847, 22.01701847, 22.01701847,
         22.01701847, 22.01701847, 22.01701847, 22.01701847, 22.01701847,
         22.01701847, 22.01701847, 22.01701847, 22.01701847, 22.01701847,
         22.01701847, 22.01701847, 22.01701847, 23.18026279, 23.18026279,
         23.18026279, 23.18026279, 23.18026279, 23.18026279, 23.18026279,
         23.18026279, 23.18026279, 23.18026279, 23.18026279, 23.18026279,
         23.18026279, 23.18026279, 23.18026279, 23.18026279]),
  89: array([15.04169521, 15.04169521, 15.041

In [6]:
from modules.stategrid import create_statespace

s = create_statespace(par)
m = Model()
init_V = m.initialize_Vstar(s, par)
interp = m.create_interp(s, init_V)
assert interp(s[30]) ==  init_V[30]


In [7]:
interp

In [8]:
s[1]

array([10.07936747,  0.        , -3.33333333])

In [16]:
interp((10.123, 1, -1.123))

array(15.04170896)

In [15]:
s[1]

array([10.07936747,  0.        , -3.33333333])

In [101]:
m, f, p = s[:, 0], s[:, 1], s[:, 2]

In [31]:
init_V

array([15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
       15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
       15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
       15.04169525, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
       20.22339078, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
       20.22339078, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
       20.22339078, 20.22339078, 22.01701847, 22.01701847, 22.01701847,
       22.01701847, 22.01701847, 22.01701847, 22.01701847, 22.01701847,
       22.01701847, 22.01701847, 22.01701847, 22.01701847, 22.01701847,
       22.01701847, 22.01701847, 22.01701847, 23.18026279, 23.18026279,
       23.18026279, 23.18026279, 23.18026279, 23.18026279, 23.18026279,
       23.18026279, 23.18026279, 23.18026279, 23.18026279, 23.18026279,
       23.18026279, 23.18026279, 23.18026279, 23.18026279])

In [33]:
m.size

64

In [41]:
interp_3d(m, f, p, init_V, 10.0, 0.0, 3.0)

TypeError: No matching definition for argument type(s) array(float64, 1d, A), array(float64, 1d, A), array(float64, 1d, A), array(float64, 1d, C), float64, float64, float64

In [35]:
k = np.array(f, dtype=np.double)

In [36]:
k.dtype

dtype('float64')

In [42]:
LinearNDInterpolator(s, Vstar)

NameError: name 'LinearNDInterpolator' is not defined

In [48]:
RegularGridInterpolator(s, init_V)

ValueError: There are 64 point arrays, but values has 1 dimensions

In [20]:
def fu(x,y,z):
    return 2 * x**3 + 3 * y**2 - z
x = np.linspace(-1, 4, 20)
y = np.linspace(4, 7, 20)
z = np.linspace(7, 9, 20)
data = fu(*np.meshgrid(x, y, z, indexing='ij', sparse=True))

In [53]:
data.shape

(11, 22, 33)

In [93]:
my_interpolating_function = RegularGridInterpolator((x, y, z), data, fill_value=None, bounds_error=False)

In [94]:
pts = np.array([1.1, 3.2, 8.3])
my_interpolating_function(pts)

array([22.82077562])

In [95]:
@njit
def some_jit_func(x, y, z):
    my_interpolating_function(x, y, z)
    

In [96]:
some_jit_func(2.1, 2.1, 3.4)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'my_interpolating_function': cannot determine Numba type of <class 'scipy.interpolate.interpolate.RegularGridInterpolator'>

File "<ipython-input-95-2c58d905aa33>", line 3:
def some_jit_func(x, y, z):
    my_interpolating_function(x, y, z)
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new


In [107]:
data = fu(*np.meshgrid(x, y, z, indexing='ij', sparse=True))
interp_3d(x, y, z, data, 10.0, 20.0, 3.0)

1365.4044321313063

In [121]:
@njit
def interpolate(x, y, z, values, x_i, y_i, z_i):
    interp = lambda x_i, y_i, z_i : interp_3d(x, y, x, values, x_i, y_i, z_i)
    return interp

In [64]:
from numba import int32, float64, jitclass, jit    # import the types

spec = [
    ('grid1', float64[:]),
    ('grid2', float64[:]),
    ('grid3', float64[:]),
    ('values', float64[:, :, :])
]

@jitclass(spec)
class Interpolate3D(object):
    def __init__(self, grid1, grid2, grid3, values):
        self.grid1 = grid1
        self.grid2 = grid2
        self.grid3 = grid3
        self.values = values
    
    @njit
    def interpolate(self, x_i, y_i, z_i):
        return interp_3d(self.grid1, self.grid2, self.grid3, self.values, x_i, y_i, z_i)


TypeError: class members are not yet supported: interpolate

In [26]:
@njit
def funcy(interp_class, x_i, y_i, z_i):
    return interp_3d(interp_class.grid1, interp_class.grid2, interp_class.grid3, interp_class.values, x_i, y_i, z_i)


In [35]:
interp = Interpolate3D(x, y, z, data)

In [41]:
interp.interpolate(1, 3, 10)

15.624289254993748

In [34]:
%time
for i in range(100000):
    res = funcy(interp, 2, 2, 4)

CPU times: user 4 µs, sys: 1e+03 ns, total: 5 µs
Wall time: 8.11 µs


In [192]:
@njit
def lars(x, y):
    f = lambda x: x + y

In [209]:
@njit
def test1(x, y, z, vgrid):
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = interp_3d(x, y, z, vgrid, x_i, y_i, z_i)
        print(res)
    
my_interpolating_function = RegularGridInterpolator((x, y, z), data, fill_value=None, bounds_error=False)
@jit
def test2():
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = my_interpolating_function(np.array([x_i, y_i, z_i]))
        print(res)

In [210]:
%%time
test1(x, y, z, data)

-136.75900276991177
CPU times: user 159 ms, sys: 4.7 ms, total: 163 ms
Wall time: 165 ms


In [211]:
%%time
test2()

[-136.75900277]
CPU times: user 203 ms, sys: 6.35 ms, total: 209 ms
Wall time: 214 ms


In [213]:
m, f, p = s[:, 0], s[:, 1], s[:, 2]


@njit
def test1(x, y, z, vgrid):
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = interp_3d(x, y, z, vgrid, x_i, y_i, z_i)
        print(res)
    
my_interpolating_function = RegularGridInterpolator((x, y, z), data, fill_value=None, bounds_error=False)
@jit
def test2():
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = my_interpolating_function(np.array([x_i, y_i, z_i]))
        print(res)

In [215]:
p

array([-10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.  

In [69]:
a, b, c = np.linspace(10,20), np.linspace(0, 10), np.linspace(20, 30 ,num=20)

In [10]:
h = np.meshgrid(a, b)

In [11]:
def func(a, b):
    return a * b - b

In [14]:
func(*h)

(50, 50)

In [42]:
from collections import namedtuple

In [43]:
nt = namedtuple('nt', ['a', 'b'])

In [53]:
hh = nt(1, 2)
hh2 = (1, 2)

In [62]:
@njit
def solve_fast(t1, t2):
    return t1 + t2

In [63]:
solve_fast(1, 2)

3

In [86]:
def utility(c, par):
    return c**(1/2)

def T_max_utility(m, f, p, par):
    return utility(m, t, par)

In [87]:
res = T_max_utility(*np.meshgrid(a, b, c, indexing='ij'), par=par)

(50, 50, 20)

In [73]:
from functools import partial

In [ ]:
partial()