In [2]:
from model import Model
from parameters import parameters as par
from modules.interp import interp_3d
import numpy as np
from scipy.interpolate import RegularGridInterpolator
from numba import njit

In [2]:
m = Model()
m.solve(par)

/Users/Jeppe/.local/share/virtualenvs/dypa_termpaper-laBhpRgB/lib/python3.7/site-packages/scipy/optimize/_minimize.py:761: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  "defaulting to absolute tolerance.", RuntimeWarning)


choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)


/Users/Jeppe/.local/share/virtualenvs/dypa_termpaper-laBhpRgB/lib/python3.7/site-packages/scipy/optimize/_minimize.py:761: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance.
  "defaulting to absolute tolerance.", RuntimeWarning)


choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=0.0)
choicetuple(c=4.468009778628238, kappa=0.0, i=1.0)
choicetuple(c=4.468009778628238, kappa=0.55, i=0.0)
choicetuple(c=4.468009

choicetuple(c=190983.62365904142, kappa=0.0, i=0.0)
choicetuple(c=190983.62365904142, kappa=0.0, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=0.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.0, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.0, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.0, i=0.0)
choicetuple(c=190983.62365904142, kappa=0.0, i=1.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=0.0)
choicetuple(c=190983.62365904142, kappa=0.55, i=1.0)


({90: array([15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
         15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
         15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
         15.04169525, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
         20.22339078, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
         20.22339078, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
         20.22339078, 20.22339078, 22.01701847, 22.01701847, 22.01701847,
         22.01701847, 22.01701847, 22.01701847, 22.01701847, 22.01701847,
         22.01701847, 22.01701847, 22.01701847, 22.01701847, 22.01701847,
         22.01701847, 22.01701847, 22.01701847, 23.18026279, 23.18026279,
         23.18026279, 23.18026279, 23.18026279, 23.18026279, 23.18026279,
         23.18026279, 23.18026279, 23.18026279, 23.18026279, 23.18026279,
         23.18026279, 23.18026279, 23.18026279, 23.18026279]),
  89: array([15.04169521, 15.04169521, 15.041

In [6]:
from modules.stategrid import create_statespace

s = create_statespace(par)
m = Model()
init_V = m.initialize_Vstar(s, par)
interp = m.create_interp(s, init_V)
assert interp(s[30]) ==  init_V[30]


In [7]:
interp

In [8]:
s[1]

array([10.07936747,  0.        , -3.33333333])

In [16]:
interp((10.123, 1, -1.123))

array(15.04170896)

In [15]:
s[1]

array([10.07936747,  0.        , -3.33333333])

In [101]:
m, f, p = s[:, 0], s[:, 1], s[:, 2]

In [31]:
init_V

array([15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
       15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
       15.04169525, 15.04169525, 15.04169525, 15.04169525, 15.04169525,
       15.04169525, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
       20.22339078, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
       20.22339078, 20.22339078, 20.22339078, 20.22339078, 20.22339078,
       20.22339078, 20.22339078, 22.01701847, 22.01701847, 22.01701847,
       22.01701847, 22.01701847, 22.01701847, 22.01701847, 22.01701847,
       22.01701847, 22.01701847, 22.01701847, 22.01701847, 22.01701847,
       22.01701847, 22.01701847, 22.01701847, 23.18026279, 23.18026279,
       23.18026279, 23.18026279, 23.18026279, 23.18026279, 23.18026279,
       23.18026279, 23.18026279, 23.18026279, 23.18026279, 23.18026279,
       23.18026279, 23.18026279, 23.18026279, 23.18026279])

In [33]:
m.size

64

In [41]:
interp_3d(m, f, p, init_V, 10.0, 0.0, 3.0)

TypeError: No matching definition for argument type(s) array(float64, 1d, A), array(float64, 1d, A), array(float64, 1d, A), array(float64, 1d, C), float64, float64, float64

In [35]:
k = np.array(f, dtype=np.double)

In [36]:
k.dtype

dtype('float64')

In [42]:
LinearNDInterpolator(s, Vstar)

NameError: name 'LinearNDInterpolator' is not defined

In [48]:
RegularGridInterpolator(s, init_V)

ValueError: There are 64 point arrays, but values has 1 dimensions

In [208]:
def fu(x,y,z):
    return 2 * x**3 + 3 * y**2 - z
x = np.linspace(-1, 4, 20)
y = np.linspace(4, 7, 20)
z = np.linspace(7, 9, 20)
data = fu(*np.meshgrid(x, y, z, indexing='ij', sparse=True))

In [53]:
data.shape

(11, 22, 33)

In [93]:
my_interpolating_function = RegularGridInterpolator((x, y, z), data, fill_value=None, bounds_error=False)

In [94]:
pts = np.array([1.1, 3.2, 8.3])
my_interpolating_function(pts)

array([22.82077562])

In [95]:
@njit
def some_jit_func(x, y, z):
    my_interpolating_function(x, y, z)
    

In [96]:
some_jit_func(2.1, 2.1, 3.4)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'my_interpolating_function': cannot determine Numba type of <class 'scipy.interpolate.interpolate.RegularGridInterpolator'>

File "<ipython-input-95-2c58d905aa33>", line 3:
def some_jit_func(x, y, z):
    my_interpolating_function(x, y, z)
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new


In [107]:
data = fu(*np.meshgrid(x, y, z, indexing='ij', sparse=True))
interp_3d(x, y, z, data, 10.0, 20.0, 3.0)

1365.4044321313063

In [121]:
@njit
def interpolate(x, y, z, values, x_i, y_i, z_i):
    interp = lambda x_i, y_i, z_i : interp_3d(x, y, x, values, x_i, y_i, z_i)
    return interp

In [191]:
from numba import int32, float64, jitclass, jit    # import the types

spec = [
    ('grid1', float64[:]),
    ('grid2', float64[:]),
    ('grid3', float64[:]),
    ('values', float64[:, :, :])
]

@jitclass(spec)
class Interpolate3D(object):
    def __init__(grid1, grid2, grid3, values):
        self.grid1 = grid1
        self.grid2 = grid2
        self.grid3 = grid3
        self.values = values
    
    def interpolate(self, x_i, y_i, z_i):
        return interp_3d(self.grid1, self.grid2, self.grid3, self.values, x_i, y_i, z_i)


In [192]:
@njit
def lars(x, y):
    f = lambda x: x + y

In [209]:
@njit
def test1(x, y, z, vgrid):
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = interp_3d(x, y, z, vgrid, x_i, y_i, z_i)
        print(res)
    
my_interpolating_function = RegularGridInterpolator((x, y, z), data, fill_value=None, bounds_error=False)
@jit
def test2():
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = my_interpolating_function(np.array([x_i, y_i, z_i]))
        print(res)

In [210]:
%%time
test1(x, y, z, data)

-136.75900276991177
CPU times: user 159 ms, sys: 4.7 ms, total: 163 ms
Wall time: 165 ms


In [211]:
%%time
test2()

[-136.75900277]
CPU times: user 203 ms, sys: 6.35 ms, total: 209 ms
Wall time: 214 ms


In [213]:
m, f, p = s[:, 0], s[:, 1], s[:, 2]


@njit
def test1(x, y, z, vgrid):
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = interp_3d(x, y, z, vgrid, x_i, y_i, z_i)
        print(res)
    
my_interpolating_function = RegularGridInterpolator((x, y, z), data, fill_value=None, bounds_error=False)
@jit
def test2():
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = my_interpolating_function(np.array([x_i, y_i, z_i]))
        print(res)

In [215]:
p

array([-10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.        ,
       -10.        ,  -3.33333333,   3.33333333,  10.  

In [132]:
import pandas as pd

In [140]:
df1 = pd.DataFrame(s, columns= ['a','b','c'])

In [141]:
df2 = pd.DataFrame(s)

In [144]:
lookup_table = pd.concat([df1, df2],axis=1)

In [146]:
lookup_table

a         b          c              0         1          2
0       10.079367  0.000000 -10.000000      10.079367  0.000000 -10.000000
1       10.079367  0.000000  -3.333333      10.079367  0.000000  -3.333333
2       10.079367  0.000000   3.333333      10.079367  0.000000   3.333333
3       10.079367  0.000000  10.000000      10.079367  0.000000  10.000000
4       10.079367  0.666667 -10.000000      10.079367  0.666667 -10.000000
5       10.079367  0.666667  -3.333333      10.079367  0.666667  -3.333333
6       10.079367  0.666667   3.333333      10.079367  0.666667   3.333333
7       10.079367  0.666667  10.000000      10.079367  0.666667  10.000000
8       10.079367  1.333333 -10.000000      10.079367  1.333333 -10.000000
9       10.079367  1.333333  -3.333333      10.079367  1.333333  -3.333333
10      10.079367  1.333333   3.333333      10.079367  1.333333   3.333333
11      10.079367  1.333333  10.000000      10.079367  1.333333  10.000000
12      10.079367  2.000000 -10.000000      10.079367  2.000000 -10.000000
13      10.079367  2.000000  -3.333333      10.079367  2.000000  -3.333333
14      10.079367  2.000000   3.333333      10.079367  2.000000   3.333333
15      10.079367  2.000000  10.000000      10.079367  2.000000  10.000000
16   16495.339765  0.000000 -10.000000   16495.339765  0.000000 -10.000000
17   16495.339765  0.000000  -3.333333   16495.339765  0.000000  -3.333333
18   16495.339765  0.000000   3.333333   16495.339765  0.000000   3.333333
19   16495.339765  0.000000  10.000000   16495.339765  0.000000  10.000000
20   16495.339765  0.666667 -10.000000   16495.339765  0.666667 -10.000000
21   16495.339765  0.666667  -3.333333   16495.339765  0.666667  -3.333333
22   16495.339765  0.666667   3.333333   16495.339765  0.666667   3.333333
23   16495.339765  0.666667  10.000000   16495.339765  0.666667  10.000000
24   16495.339765  1.333333 -10.000000   16495.339765  1.333333 -10.000000
25   16495.339765  1.333333  -3.333333   16495.339765  1.333333  -3.333333
26   16495.339765  1.333333   3.333333   16495.339765  1.333333   3.333333
27   16495.339765  1.333333  10.000000   16495.339765  1.333333  10.000000
28   16495.339765  2.000000 -10.000000   16495.339765  2.000000 -10.000000
29   16495.339765  2.000000  -3.333333   16495.339765  2.000000  -3.333333
..            ...       ...        ...            ...       ...        ...
34  138030.191932  0.000000   3.333333  138030.191932  0.000000   3.333333
35  138030.191932  0.000000  10.000000  138030.191932  0.000000  10.000000
36  138030.191932  0.666667 -10.000000  138030.191932  0.666667 -10.000000
37  138030.191932  0.666667  -3.333333  138030.191932  0.666667  -3.333333
38  138030.191932  0.666667   3.333333  138030.191932  0.666667   3.333333
39  138030.191932  0.666667  10.000000  138030.191932  0.666667  10.000000
40  138030.191932  1.333333 -10.000000  138030.191932  1.333333 -10.000000
41  138030.191932  1.333333  -3.333333  138030.191932  1.333333  -3.333333
42  138030.191932  1.333333   3.333333  138030.191932  1.333333   3.333333
43  138030.191932  1.333333  10.000000  138030.191932  1.333333  10.000000
44  138030.191932  2.000000 -10.000000  138030.191932  2.000000 -10.000000
45  138030.191932  2.000000  -3.333333  138030.191932  2.000000  -3.333333
46  138030.191932  2.000000   3.333333  138030.191932  2.000000   3.333333
47  138030.191932  2.000000  10.000000  138030.191932  2.000000  10.000000
48  500000.000000  0.000000 -10.000000  500000.000000  0.000000 -10.000000
49  500000.000000  0.000000  -3.333333  500000.000000  0.000000  -3.333333
50  500000.000000  0.000000   3.333333  500000.000000  0.000000   3.333333
51  500000.000000  0.000000  10.000000  500000.000000  0.000000  10.000000
52  500000.000000  0.666667 -10.000000  500000.000000  0.666667 -10.000000
53  500000.000000  0.666667  -3.333333  500000.000000  0.666667  -3.333333
54  500000.000000  0.666667   3.333333  500000.000000  0.666667   3.333333
55  500000.000000  0.666667  10.000000  5

In [3]:
a, b = np.linspace(10,20), np.linspace(0, 10)

In [10]:
h = np.meshgrid(a, b)

In [11]:
def func(a, b):
    return a * b - b

In [14]:
func(*h)

(50, 50)

(50,)