In [1]:
from model import Model
from parameters import parameters as par
from modules.interp import interp_3d
import numpy as np
from scipy.interpolate import RegularGridInterpolator
from numba import njit
from scipy.optimize import minimize

In [2]:
m = Model()
m.solve(par)

NameError: name 'create_statespace' is not defined

In [ ]:
from modules.stategrid import create_statespace

s = create_statespace(par)
m = Model()
init_V = m.initialize_Vstar(s, par)
interp = m.create_interp(s, init_V)
assert interp(s[30]) ==  init_V[30]


In [ ]:
interp

In [ ]:
s[1]

In [ ]:
interp((10.123, 1, -1.123))

In [ ]:
s[1]

In [ ]:
m, f, p = s[:, 0], s[:, 1], s[:, 2]

In [ ]:
init_V

In [ ]:
m.size

In [ ]:
interp_3d(m, f, p, init_V, 10.0, 0.0, 3.0)

In [ ]:
k = np.array(f, dtype=np.double)

In [ ]:
k.dtype

In [ ]:
LinearNDInterpolator(s, Vstar)

In [ ]:
RegularGridInterpolator(s, init_V)

In [ ]:
def fu(x,y,z):
    return 2 * x**3 + 3 * y**2 - z
x = np.linspace(-1, 4, 20)
y = np.linspace(4, 7, 20)
z = np.linspace(7, 9, 20)
data = fu(*np.meshgrid(x, y, z, indexing='ij', sparse=True))

In [ ]:
data.shape

In [ ]:
my_interpolating_function = RegularGridInterpolator((x, y, z), data, fill_value=None, bounds_error=False)

In [ ]:
pts = np.array([1.1, 3.2, 8.3])
my_interpolating_function(pts)

In [ ]:
@njit
def some_jit_func(x, y, z):
    my_interpolating_function(x, y, z)
    

In [ ]:
some_jit_func(2.1, 2.1, 3.4)

In [ ]:
data = fu(*np.meshgrid(x, y, z, indexing='ij', sparse=True))
interp_3d(x, y, z, data, 10.0, 20.0, 3.0)

In [ ]:
@njit
def interpolate(x, y, z, values, x_i, y_i, z_i):
    interp = lambda x_i, y_i, z_i : interp_3d(x, y, x, values, x_i, y_i, z_i)
    return interp

In [84]:
from numba import int32, float64, jitclass, jit    # import the types

spec = [
    ('grid1', float64[:]),
    ('grid2', float64[:]),
    ('grid3', float64[:]),
    ('values', float64[:, :, :])
]

@jitclass(spec)
class Interpolate3D(object):
    def __init__(self, grid1, grid2, grid3, values):
        self.grid1 = grid1
        self.grid2 = grid2
        self.grid3 = grid3
        self.values = values
    
    def interpolate(self, x_i, y_i, z_i):
        return interp_3d(self.grid1, self.grid2, self.grid3, self.values, x_i, y_i, z_i)


In [ ]:
@njit
def funcy(interp_class, x_i, y_i, z_i):
    return interp_3d(interp_class.grid1, interp_class.grid2, interp_class.grid3, interp_class.values, x_i, y_i, z_i)


In [ ]:
interp = Interpolate3D(x, y, z, data)

In [ ]:
interp.interpolate(1, 3, 10)

In [ ]:
%time
for i in range(100000):
    res = funcy(interp, 2, 2, 4)

In [ ]:
@njit
def lars(x, y):
    f = lambda x: x + y

In [ ]:
@njit
def test1(x, y, z, vgrid):
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = interp_3d(x, y, z, vgrid, x_i, y_i, z_i)
        print(res)
    
my_interpolating_function = RegularGridInterpolator((x, y, z), data, fill_value=None, bounds_error=False)
@jit
def test2():
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = my_interpolating_function(np.array([x_i, y_i, z_i]))
        print(res)

In [ ]:
%%time
test1(x, y, z, data)

In [ ]:
%%time
test2()

In [ ]:
m, f, p = s[:, 0], s[:, 1], s[:, 2]


@njit
def test1(x, y, z, vgrid):
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = interp_3d(x, y, z, vgrid, x_i, y_i, z_i)
        print(res)
    
my_interpolating_function = RegularGridInterpolator((x, y, z), data, fill_value=None, bounds_error=False)
@jit
def test2():
    for i in range(1):
        x_i, y_i, z_i = -8, -2, 4
        res = my_interpolating_function(np.array([x_i, y_i, z_i]))
        print(res)

In [ ]:
p

In [ ]:
a, b, c = np.linspace(10,20), np.linspace(0, 10), np.linspace(20, 30 ,num=20)

In [ ]:
h = np.meshgrid(a, b)

In [ ]:
def func(a, b):
    return a * b - b

In [ ]:
func(*h)

In [ ]:
from collections import namedtuple

In [ ]:
nt = namedtuple('nt', ['a', 'b'])

In [ ]:
hh = nt(1, 2)
hh2 = (1, 2)

In [ ]:
@njit
def solve_fast(t1, t2):
    return t1 + t2

In [ ]:
solve_fast(1, 2)

In [ ]:
def utility(c, par):
    return c**(1/2)

def T_max_utility(m, f, p, par):
    return utility(m, t, par)

In [ ]:
res = T_max_utility(*np.meshgrid(a, b, c, indexing='ij'), par=par)

In [ ]:
from functools import partial

In [ ]:
partial()

In [ ]:
np.empty(shape=(10, 10 ,10))

In [ ]:
l = np.linspace(10, 10).shape[0]

In [ ]:
import pickle
pickle.loads(pickle.dumps(l))

In [ ]:
d_, j_ = np.array([1,2,3]), np.array([4, 5])

In [ ]:
dd, jj = np.meshgrid(d, j, indexing='ij')

In [ ]:
for i in range(len(d_)):
    for j in range(len(j_)):
        print(jj[i,j])
    

In [7]:
def utility(c, kappa, i):
    return c * kappa * i

In [8]:
kappas = np.array([0.0, 0.55])
iss = np.array([0, 1])

In [10]:
V, C = np.inf, None
for kappa in np.array([0.0, 0.55]):
    for i in np.array([0, 1]):
        _utility = lambda x: - utility(x, kappa, i)
        sol = minimize(fun=_utility, x0=[0.1], bounds=[(0.1, 100.0)])
        _V, _C = sol.fun[0], (sol.x[0], kappa, i)
        if V > _V:
            V, C = _V, _C

print(V, C)

-55.00000000000001 (100.0, 0.55, 1)


In [ ]:
for i in np.random.randint(0, 10, size=(5, 6, 7)):
    

In [ ]:
aa, bb, cc = np.meshgrid(a, b, c, indexing='ij')

In [ ]:
for i in range(aa.size):
    print(aa[i], bb[i], cc[i])

In [ ]:
aa.shape

In [3]:
from modules.stategrid import create_statespace

In [11]:
from modules.stategrid import create_grids

In [71]:
par.Nm, par.Nf, par.Np  = 40, 25, 25
sp = create_statespace(par) #statespace
m_grid, f_grid, p_grid = create_grids(par)

In [72]:
v = utility(*sp.T)#vstar

In [147]:
def create_lookup_dict(statespace, Vstar):
    d = dict()
    for i in range(statespace.shape[0]):
        key, value = statespace[i], Vstar[i]
        d[tuple(key)] = value
    return d

In [154]:
ld = create_lookup_dict(sp, v)

In [155]:
def create_mesh(m_grid, f_grid, p_grid, lookup_dict, par):
    res = np.empty(shape=(par.Nm, par.Nf, par.Np))
    
    for m_ix in range(par.Nm):
        for f_ix in range(par.Nf):
            for p_ix in range(par.Np):
                tup = (m_grid[m_ix], f_grid[f_ix], p_grid[p_ix])
                res[m_ix, f_ix, p_ix] = lookup_dict[tup]
                
    return res

In [158]:
%%time
ld = create_lookup_dict(sp, v)
create_mesh(m_grid, f_grid, p_grid, ld, par)

CPU times: user 81.8 ms, sys: 5.41 ms, total: 87.2 ms
Wall time: 88.7 ms


In [90]:
VVstar = create_mesh(m_grid, f_grid, p_grid, par)

from numba import int32, float64, jitclass, jit    # import the types

spec = [
    ('grid1', float64[:]),
    ('grid2', float64[:]),
    ('grid3', float64[:]),
    ('values', float64[:, :, :])
]

@jitclass(spec)
class Interpolate3D(object):
    def __init__(self, grid1, grid2, grid3, values):
        self.grid1 = grid1
        self.grid2 = grid2
        self.grid3 = grid3
        self.values = values
    
    def interpolate(self, x_i, y_i, z_i):
        return interp_3d(self.grid1, self.grid2, self.grid3, self.values, x_i, y_i, z_i)


In [105]:
my_interp1 = RegularGridInterpolator((m_grid, f_grid, p_grid), VVstar, fill_value=None, bounds_error=False)
my_interp2 = Interpolate3D(m_grid, f_grid, p_grid, VVstar)

##

In [106]:
d[tuple(sp[100])]

-33.597894663863286

In [109]:

_m, _f, _p = tuple(sp[100])


array(-33.59789466)

In [116]:
def t1():
    for i in range(10000):
        my_interp1((_m, _f, _p))

def t2():
    for i in range(10000):
        my_interp2.interpolate(_m, _f, _p)

In [127]:
%%time 
t2()

CPU times: user 15.6 ms, sys: 205 µs, total: 15.8 ms
Wall time: 16 ms


In [135]:
my_interp2.interpolate(2,123,1)

245.99999999999457

In [66]:
print(_m, _f, _p)

10.079368399158986 1.3333333333333333 3.333333333333334


In [26]:
def mesh_lookup(m, f, p):
    print(m)
    #print(m, f, p)
    return d[tuple(m, f, p)]

In [27]:
mesh_lookup(*np.meshgrid(m_grid, f_grid, p_grid, indexing='ij'))

[[[1.00793684e+01 1.00793684e+01 1.00793684e+01 1.00793684e+01]
  [1.00793684e+01 1.00793684e+01 1.00793684e+01 1.00793684e+01]
  [1.00793684e+01 1.00793684e+01 1.00793684e+01 1.00793684e+01]
  [1.00793684e+01 1.00793684e+01 1.00793684e+01 1.00793684e+01]]

 [[1.64953382e+04 1.64953382e+04 1.64953382e+04 1.64953382e+04]
  [1.64953382e+04 1.64953382e+04 1.64953382e+04 1.64953382e+04]
  [1.64953382e+04 1.64953382e+04 1.64953382e+04 1.64953382e+04]
  [1.64953382e+04 1.64953382e+04 1.64953382e+04 1.64953382e+04]]

 [[1.38030186e+05 1.38030186e+05 1.38030186e+05 1.38030186e+05]
  [1.38030186e+05 1.38030186e+05 1.38030186e+05 1.38030186e+05]
  [1.38030186e+05 1.38030186e+05 1.38030186e+05 1.38030186e+05]
  [1.38030186e+05 1.38030186e+05 1.38030186e+05 1.38030186e+05]]

 [[5.00000000e+05 5.00000000e+05 5.00000000e+05 5.00000000e+05]
  [5.00000000e+05 5.00000000e+05 5.00000000e+05 5.00000000e+05]
  [5.00000000e+05 5.00000000e+05 5.00000000e+05 5.00000000e+05]
  [5.00000000e+05 5.00000000e+05 5

TypeError: tuple expected at most 1 arguments, got 3

In [41]:
m_grid

array([1.00793684e+01, 1.64953382e+04, 1.38030186e+05, 5.00000000e+05])

In [159]:
@njit
def can_take_class(par):
    return par.Nf

can_take_class(par)

25

In [161]:
np.array([1, 2, 3.2]).dtype

dtype('float64')

In [163]:
from numba import types

In [164]:
types.__dir__()

['__name__',
 '__doc__',
 '__package__',
 '__loader__',
 '__spec__',
 '__path__',
 '__file__',
 '__cached__',
 '__builtins__',
 'print_function',
 'division',
 'absolute_import',
 'struct',
 'np',
 'utils',
 'abstract',
 'ABCMeta',
 'abstractmethod',
 'abstractproperty',
 'itertools',
 'weakref',
 'add_metaclass',
 'cached_property',
 'Type',
 'Dummy',
 'Hashable',
 'Number',
 'Callable',
 'DTypeSpec',
 'IterableType',
 'Sized',
 'ConstSized',
 'IteratorType',
 'Container',
 'Sequence',
 'MutableSequence',
 'ArrayCompatible',
 'Literal',
 'TypeRef',
 'common',
 'misc',
 'containers',
 'Opaque',
 'SimpleIterableType',
 'SimpleIteratorType',
 'Buffer',
 'Undefined',
 'unliteral',
 'Conversion',
 'TypingError',
 'Pair',
 'BaseContainerIterator',
 'BaseContainerPayload',
 'Bytes',
 'ByteArray',
 'PyArray',
 'MemoryView',
 'is_homogeneous',
 'BaseTuple',
 'BaseAnonymousTuple',
 'UniTuple',
 'UniTupleIter',
 'Tuple',
 'BaseNamedTuple',
 'NamedUniTuple',
 'NamedTuple',
 'List',
 'ListIter',
 